### ISSUE TITLE
test case not working

### ISSUE THREAD

**Issue by Ryaen** [shivamd20/blicode#5]
Irrespective of writing correct code in any language for default problem no.3 i.e. finding the sum of angles of triangle. The test case is not working. It is always showing "YES" and sample test case failed.

**Comment by shivamd20** [comment]
@Ryaen  Use secret key ```test1```. I did changed the output of problem 3 for testing purpose. Cross check your code's output with the test cases  and also check for the end-line character. The test cases of problem 3 are also wrongly feeded .

**Comment by shivamd20** [comment]
working
